POST https://node-do-zero-8a7t.onrender.com/videos
Content-Type: application/json

{
  "title": "Video Node",
  "description": "Esse é o video 01",
  "duration": 180
}

###

GET https://node-do-zero-8a7t.onrender.com/videos


###
PUT https://node-do-zero-8a7t.onrender.com/videos/8d063683-58c5-4d98-a14b-dcdd118011e0
Content-Type: application/json

{
  "title": "Video 3",
  "description": "Esse é o video 3",
  "duration": 180
}


###
DELETE https://node-do-zero-8a7t.onrender.com/videos/8d063683-58c5-4d98-a14b-dcdd118011e0